= Methods Documentation

Data from LWN's article (https://lwn.net/Articles/922405/[Link]) and sched-ext documentation (https://github.com/sched-ext/sched_ext/blob/sched_ext/Documentation/scheduler/sched-ext.rst[Link])

== Introduction to concept
The core idea behind BPF is that it allows programs [.underline]#to be loaded into the kernel from user space at run time#.

The linux scheduler is not a single one, as there are the *CFS, realtime and deadline scheduler*, even though the majority of the program are managed by the CFS. Sched-ext allow to have dedicate scheduler for workload.

== Scheduling with BPF
The proposed patch adds a *new scheduling class* called SCHED_EXT that can be [.underline]#selected with ```sched_setscheduler()```# call like others (except SCHED_DEADLINE). 

It is an *unprivilaged* class so any process can put themself in this class and it is placed *between SCHED_IDLE and SCHED_NORMAL*. This make it impossible to take over the system with a SCHED_EXT scheduler, preventing application from running as SCHED_NORMAL. Also, [.underline]#it suggest that when a SCHED_EXT scheduler is load most the process will be handled by this#, if no such scheduler is loaded process in the SCHED_EXT are run with as if they where is SCHED_NORMAL. A BPF scheduler can *move all running process into SCHED_EXT* (only the ones below realtime priority) with the call ```scx_bpf_switch_all()```.

=== Queues, callbacks and functions
A BPF scheduler will manage a set of *dispatch queue* ([.underline]#normally one per CPU plus one global#), which runnable tasks waiting for a CPU. When a CPU is ready to run the scheduler removes a task from the relevant dispatch queue and gives it to the CPU.

A BPF scheduler is mostly implemented as a *set of callback to be invoked via an operations structures*, every of which inform the BPF of an [.underline]#event of a decision to be made#. Some of the callback are:

. ```prep_enable(), enable()```: inform that a process is *entering SCHED_EXT* class, and can be used to set up associated data. The first call is allowed to block and is used for [.underline]#memory alocations#, while the second cannot block but is the one to actually [.underline]#enabling scheduling# for the new task.
. ```select_cpu()```: *select a CPU for a task that is just waking up*, it should return the number of the CPU to place the task on (which can be changed again before running it). This decision [.underline]#may be used by the scheduler to wake the selected CPU# if it is currently idle. 
. ```enqueue()```: *Enqueue a task into the scheduler* for running. [.underline]#Normally# it call ```scx_bpf_dispatch()``` to [.underline]#place a task into a chosen dispatch queue#, from which it will eventually be run.
    * this call should provide the *lenght of time slice* the task will have once it runs. 
        ** If the speciefied as SCX_SLICE_INF, it will go into *tickless mode*
    * enque is *not required* to put in any dispatch queue and it could stash it somewhere for sometime. But the [.underline]#kernel ensure that a process is not forgotten for more than 30 seconds# (by default, can be reduced and not increased).
. ```dispatch()```: called on *empty CPU dispatch queue* to assign new task to keep cpu busy.
    * If it remain empty [.underline]#the scheduler (?) will try to grab some from the global queue#.
. ```update_idle()```: inform the scheduler of a *CPU leaving or entering idle*.
. ```runnable(), running(), stopping(), queiscent()```: inform the scheduler of a *status changes for a task* (call respectively when a task: become runnable, start running on CPU, is taken off a CPU, is no longer runnable).
. ```cpu_acquire(), cpu_release()```: inform scheduler of *availability change of a CPU*. Example of cpu_release is when a realtime scheduling class claim a CPU to manage.

// 

* Full list at https://github.com/sched-ext/sched_ext/blob/sched_ext/include/linux/sched/ext.h[github link sched/ext.h], plus other resourse at end of https://github.com/sched-ext/sched_ext/blob/sched_ext/Documentation/scheduler/sched-ext.rst[sched-ext rust documentation].

There are also *function* that can be called by the scheduler can call to [.underline]#affect scheduling decision#. For example ```scx_bpf_kick_cpu``` can be called to preempt a task tha is running on a CPU (removing it) and them call back the scheduler to pick a new task to run there.
