= Teacher Meeting Notes

== First notes of meeting
*Objective short term*: sched_set[/get]attr (+chrt with command line) and install man pages.
*Longer term objectives*: testing sched_ext with following strategy:

. *cpu affinity mask*: which tell the scheduler where in which core a process can be executed (in simple is a array of bit of length the same as the number of core, where 1 means that it can run on that core and viceversa);
. *rt-app*: for creating artificial workload based on a config file
. *trace-cmd and kernelshark*: to save a recording of event (for use are important the sched events) and to visualize them.
	.. *litrace.h*: provides binding for c. It is a tool of Steven Rostedt (event/fs (?))
. *using the *get[/set]attr* to change policy of the workload and running only that on sched_ext
. creating a *table* with on an axis if there is [.underline]#deadline worload and on the other which scheduler is running# CFS (/EEVDF) or sched_ext

== Second Notes of meeting
*Objective long term*: tracing with trace-cmd the events sched_all (to not lose any) or sched_switch, with no filter or filtering by PID. Than it execute for some interval the scheduler with [.underline]#1ms task timeout and then double# it for the same interval.

We would like to remove everything from some core but for ease peraphs is better to use two different shell, one for login and one for the workload.

*Extra*:
. analysis of fair scheduling with n task with wi weigth
. check to see if hyperthreading influence the time they run, running workload as such `[a/\_] [b/_] [c/d]`


=== Useful tools
. *cscope*: for an in deep analysis of c project
. *pahole _*: gives implementation of given argument (ex. rq (runqueue), task_struct. sched_entity)

=== Notes
Remember to register to may stage.

== Third Notes of meeting (without Bini)
*Objecives*:

. [.underline]#affinity mask#: on same cpu using sched_setaffinity;
	.. if it doesn't work (it does so i can ignore it) i can use cpu_set;
	.. sched_deadline for example i cannot set affinity but i can use a cpu_set because they are mutually exclusive;
. [.underline]#1ms then 2ms#: i can use the timer and set internally or do something similar from the ./double.sh and set externally (with sleep)
. [.underline]#print work done# by both process (to compare)

=== How to do a cpu-set
[%collapsible]
===========
``` bash
mkdir /dev/cpuset
mount -t cgroup -o cpuset cpuset /dev/cpuset # mount filesystem cpuset -> must be done every time
cd /dev/cpuset
mkdir testingTardiness # new cpuset -> automatically generate files
echo "5" > testingTardiness/cpuset.cpus # only core 5
echo "0,1,2,3,4" > cpuset.cpus  # should give error
echo 0 > testingTardiness/cpuset.mems # make memory exclusive (?)
echo 1 > cpuset.cpu_exclusive # make set exclusive
echo 0 > cpuset.sched_load_balance # the rest is for more separation
echo 1 > testingTardiness/cpuset.cpu_exclusive
echo 1 > testingTardiness/cpuset.mem_exclusive
echo $$ > testingTardiness/tasks # this put the actual pid in the cpuset

# is removed with rm -fr /dev/cpuset
# must be runned as root
```
===========

