= Video Interview
Linux Kernel Scheduler Developer | David Vernet (Tech Over Tea)

Summary of video (https://www.youtube.com/watch?v=Ta0imAIz31M[Link to Video])

== Scheduler's problem space
Every machine has a finite number of cores and job of the sheduler is to decide *which process to run on which core*. The scheduler want to balance the workload, running as many process in [.underline]#parallel# as possible, but it also has to account for the fact that moving a process to another core away from [.underline]#warm/hot caches#, could increase pagefault and reduce overall performance. 

It also require a *load balancing*, which devide the load amonst the cores. The load ...

Other problems of the scheduler are *fairness* and *Interactivity*. A good metrics for the scheduler is IPS meaning Instruction Per Seconds.

The linux kernel initally used *CFS* (Completely Fair Scheduler) from 2006/2007(?) until 6.6 and then it switched to *EEVDF* (Earliest Eligible Virtual Deadline First). 

Scheduler are becaming harder to write because of more various [.underline]#hardware and workload#. For example, a VM has "virtual core" which are seen to the scheduler as threads, and in certain situation it is better to fix this threads to single core and avoid as much as possible to stop these threads.

== CFS
The idea is to count *Virtual Runtime*, the time the process run for in total, and then you want to give to the one that has run for the least amount of time. In this calculation *priority (niceness)* is used to give more time to process with higher priority by [.underline]#inverve scaling# of time accumulated (divide by priority).

== EEVDF
Still has the Virtual Runtime but in addition it has a *deadline* which is summed to the Virtual Runtime to obtain a higher level of interactivity.

== Sched_ext
sched_ext and is a new *pluggable scheduling framework*, which lets you implement your own host wide scheduling policies as what are called BPF programs.

. *Host wide*: it migrate all thread to your own scheduler except the [.underline]#real-time(/deadline)# threads, which are higher priority and remain in the kernel.
. *eBPF*: let you run a jit (Just In Time) in the kernel, it has a specific istruction set and encoding for the istruction. During runtime it will read this BPF byte code and emit x86,arm,... istructions to run the program in to the kernel.
    .. There is a backend for the llvm (Compiler backend for multiple programming languages) that can compile c code into BPF instructions.
    .. Initially the name come from Packet Filtering (BPF = Berkeley Packet Filter) but then it extended (eBPF) and now it is no longer an acronym for something.
    .. BPF programs *cannot crash the kernel* because it is [.underline]#statically analysed# by the *verifier* and it it could be potentially unsafe (like reading a pointer that shouldn't be read, has a memory leak,...) then it won't load the program into the kernel.
    .. Can *interact with userspace* from your BPF program with data structure called *maps*, real time shared memory readable and writible from both userspace and kernel space.

== What are problem Sched_ext solve
CFS and EEDVF are general purpose, fair and worked for many years, but:

. it it *hard to test*, because of long compilation time and possibility of breakage. BPF program are faster to recompile entire kernel and can dynamically loaded.
. cannot have a highest performace for *specific usecase* because it need to be general purpose.
. api it is *difficult to understand* and require low level knowlenge. Meanwhile api in sched_ext are more intuitive and abstract some of the complexity.

//-

* the *overhead* of sched_ext exist, for example for the translation of the BPF istruction but it is *minor* (a couple tens of a percentage)
    * That is because *BPF is not userspace* framework, instead the kernel call your program when still being in kernelspace so the most important part remain in the kernel with no handshake but you [.underline]#can build userspace component above that# (often load balancing is done in userspace for ease). 

Restart from 29:50.